pipeline {
    agent any 

stages {

    stage("clean install")
    {
        steps{
            sh 'mvn -f ./backend/eureka/ clean install'
            sh 'mvn -f ./backend/gateway/ clean install'
            sh 'mvn -f ./backend/auth/ clean install'
        }
    }

    stage("docker-clean")
    {
        steps 
        {
            sh 'docker stop $(docker ps -a -q)'
        }
    }

    stage("docker-build")
    {
        steps {
            sh 'docker build -t eureka_service ./backend/eureka/'
            sh 'docker build -t gateway_service ./backend/gateway/'
            sh 'docker build -t auth_service ./backend/auth/'
        }
    }

    stage("docker-run")
    {
        steps {
            sh 'docker run -dp 8761:8761 eureka_service' 
            sh 'docker run -dp 7777:7777 gateway_service &'
            sh 'docker run -dp 8888:8888 auth_service &'
        }
    }
}
}