pipeline {
    agent any 

stages {

    stage("build")
    {
        steps{
            sh 'mvn -f ./backend/gateway/ clean install'
            sh 'docker build -t gateway_service ./backend/gateway/'
            sh 'docker run -dp 7777:7777'
        }
    }

    stage("test")
    {
        steps {
            echo "hi from jenkins during test"
        }
    }

    stage("docker-deploy")
    {
        steps {
            echo "hi from jenkin during docker deploy"
        }
    }
}
}